apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-demo
  template:
    metadata:
      labels:
        app: security-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
