apiVersion: v1
kind: Config
clusters:
- name: bouncer_webhook
  cluster:
    server: https://127.0.0.1:1323/image_policy

contexts:
- name: bouncer_validator
  context:
    cluster: bouncer_webhook
    user: api-server

current-context: bouncer_validator

users:
- name: api-server
  user: {}
